version: "3.9"
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8080 app:app
    env_file:
      - .env
    ports:
      - "8001:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=8080"
      - "traefik.http.routers.uglysweater.rule=Host(`xmas.vmlgermany.com`)"
      - "traefik.http.routers.uglysweater.entrypoints=websecure"
      - "traefik.http.routers.uglysweater.tls.certresolver=letsencrypt"
    volumes:
        - ./.vault:/app/.vault
