version: "3.9"
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8080 app:app
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:8080"
    volumes:
        - ./.vault:/app/.vault
