version: "3.9"
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8080 app:app
    env_file:
      - .env
    ports:
      - "8001:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=8080"
      - "traefik.http.routers.web.rule=Host(`xmas.vmlgermany.com`)"
      # FORCE HTTP ENTRYPOINT ONLY
      - "traefik.http.routers.web.entrypoints=http" 
      # (Note: Coolify usually calls it 'http' or 'web'. Try 'http' first, if that fails, try 'web')
  
    volumes:
        - ./.vault:/app/.vault
