version: "3.9"
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8080 app:app
    env_file:
      - .env
    expose:
      - "8080"
    volumes:
        - ./.vault:/app/.vault
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=8080"
