version: "3.9"
services:
  web:
    build: .
    command: sh -c "gunicorn --bind 0.0.0.0:${PORT:-8001} app:app"
    environment:
      - PORT=${PORT:-8001}
    env_file:
      - .env
    ports:
      - "${PORT:-8001}:${PORT:-8001}"
    volumes:
        - ./.vault:/app/.vault
